<?php

use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\ChatController;
use App\Http\Controllers\Api\ContestController;
use App\Http\Controllers\Api\EarningsController;
use App\Http\Controllers\Api\FeedController;
use App\Http\Controllers\Api\FollowController;
use App\Http\Controllers\Api\MemoryController;
use App\Http\Controllers\Api\NotificationController;
use App\Http\Controllers\Api\PostController;
use App\Http\Controllers\Api\ProfileController;
use App\Http\Controllers\Api\UserBlockController;
use App\Http\Controllers\Api\UserSearchController;
use Illuminate\Support\Facades\Route;

Route::prefix('auth')->group(function (): void {
    Route::post('/register', [AuthController::class, 'register']);
    Route::post('/login', [AuthController::class, 'login']);
    Route::post('/google-login', [AuthController::class, 'googleLogin']);
    Route::post('/apple-login', [AuthController::class, 'appleLogin']);
    Route::post('/forgot-password', [AuthController::class, 'forgotPassword']);
    Route::post('/reset-password', [AuthController::class, 'resetPassword']);
    Route::get('/verify-email/{id}/{token}', [AuthController::class, 'verifyEmail'])->name('auth.verify-email');
});

Route::middleware('session.auth')->group(function (): void {
    Route::get('/feed/home', [FeedController::class, 'home']);
    Route::get('/earnings/overview', [EarningsController::class, 'overview']);
    Route::get('/earnings/breakdowns', [EarningsController::class, 'breakdowns']);
    Route::get('/earnings/withdrawals', [EarningsController::class, 'withdrawals']);
    Route::post('/earnings/withdrawals', [EarningsController::class, 'storeWithdrawal']);
    Route::get('/feed/posts/{postId}', [FeedController::class, 'show']);
    Route::get('/feed/posts/{postId}/comments', [FeedController::class, 'comments']);
    Route::post('/feed/posts/{postId}/like', [FeedController::class, 'toggleLike']);
    Route::post('/feed/posts/{postId}/save', [FeedController::class, 'toggleSave']);
    Route::post('/feed/posts/{postId}/share', [FeedController::class, 'share']);
    Route::post('/feed/posts/{postId}/vote', [FeedController::class, 'vote']);
    Route::post('/feed/posts/{postId}/comments', [FeedController::class, 'comment']);
    Route::post('/feed/comments/{commentId}/like', [FeedController::class, 'toggleCommentLike']);
    Route::post('/feed/comments/{commentId}/replies', [FeedController::class, 'reply']);
    Route::post('/feed/replies/{replyId}/like', [FeedController::class, 'toggleReplyLike']);
    Route::get('/reels', [FeedController::class, 'reels']);
    Route::get('/reels/{postId}', [FeedController::class, 'reelShow']);
    Route::get('/reels/{postId}/comments', [FeedController::class, 'reelComments']);
    Route::post('/reels/{postId}/like', [FeedController::class, 'toggleLike']);
    Route::post('/reels/{postId}/save', [FeedController::class, 'toggleSave']);
    Route::post('/reels/{postId}/share', [FeedController::class, 'share']);
    Route::post('/reels/{postId}/vote', [FeedController::class, 'vote']);
    Route::post('/reels/{postId}/comments', [FeedController::class, 'comment']);
    Route::get('/profile/me', [ProfileController::class, 'me']);
    Route::patch('/profile/me', [ProfileController::class, 'update']);
    Route::get('/profile/me/username-availability', [ProfileController::class, 'usernameAvailability']);
    Route::get('/profile/me/overview', [ProfileController::class, 'overview']);
    Route::patch('/profile/me/overview', [ProfileController::class, 'updateOverview']);
    Route::post('/profile/me/verify', [ProfileController::class, 'verify']);
    Route::get('/profile/me/images', [ProfileController::class, 'images']);
    Route::get('/profile/me/avatar', [ProfileController::class, 'avatar']);
    Route::get('/profile/me/blocked-users', [UserBlockController::class, 'index']);
    Route::post('/profile/me/avatar', [ProfileController::class, 'uploadAvatar']);
    Route::get('/profile/me/cover', [ProfileController::class, 'cover']);
    Route::post('/profile/me/cover', [ProfileController::class, 'uploadCover']);
    Route::get('/profiles/{username}/overview', [ProfileController::class, 'publicOverview']);
    Route::get('/profiles/{username}', [ProfileController::class, 'show']);
    Route::post('/profiles/{username}/follow', [FollowController::class, 'follow']);
    Route::post('/profiles/{username}/block', [UserBlockController::class, 'toggle']);
    Route::delete('/profiles/{username}/follow', [FollowController::class, 'unfollow']);
    Route::get('/profiles/{username}/followers', [FollowController::class, 'followers']);
    Route::get('/profiles/{username}/following', [FollowController::class, 'following']);
    Route::get('/profiles/{username}/ratings-distribution', [ProfileController::class, 'ratingsDistribution']);
    Route::post('/posts', [PostController::class, 'store']);
    Route::match(['put', 'patch'], '/posts/{postId}', [PostController::class, 'update']);
    Route::delete('/posts/{postId}', [PostController::class, 'destroy']);
    Route::post('/posts/{postId}/repost', [PostController::class, 'repost']);
    Route::get('/memories', [MemoryController::class, 'index']);
    Route::get('/memories/{memoryId}', [MemoryController::class, 'show']);
    Route::post('/memories', [MemoryController::class, 'store']);
    Route::match(['put', 'patch'], '/memories/{memoryId}', [MemoryController::class, 'update']);
    Route::delete('/memories/{memoryId}', [MemoryController::class, 'destroy']);
    Route::delete('/memories/{memoryId}/media/{mediaId}', [MemoryController::class, 'destroyMedia']);
    Route::post('/memories/{memoryId}/favorite', [MemoryController::class, 'toggleFavorite']);
    Route::get('/users/search', [UserSearchController::class, 'index']);
    Route::get('/chats', [ChatController::class, 'index']);
    Route::post('/chats/initialize', [ChatController::class, 'initialize']);
    Route::get('/chats/{username}/messages', [ChatController::class, 'messages']);
    Route::post('/chats/{conversationId}/messages', [ChatController::class, 'sendMessage']);
    Route::post('/chats/{conversationId}/stop', [ChatController::class, 'stopMessaging']);
    Route::post('/chats/{conversationId}/resume', [ChatController::class, 'resumeMessaging']);
    Route::patch('/profile/me/presence', [ChatController::class, 'updatePresence']);
    Route::get('/notifications', [NotificationController::class, 'index']);
    Route::patch('/notifications/read-all', [NotificationController::class, 'readAll']);
    Route::patch('/notifications/{notificationId}/read', [NotificationController::class, 'read']);
    Route::delete('/notifications/{notificationId}', [NotificationController::class, 'destroy']);
    Route::delete('/notifications/clear', [NotificationController::class, 'clear']);

    Route::get('/contests/home', [ContestController::class, 'home']);
    Route::get('/contests/admin', [ContestController::class, 'adminContests']);
    Route::get('/contests/meta/users', [ContestController::class, 'users']);
    Route::get('/contests/meta/cities', [ContestController::class, 'cities']);
    Route::get('/contests/meta/tags', [ContestController::class, 'tags']);
    Route::get('/contests/profile/results', [ContestController::class, 'profileResults']);
    Route::get('/contests/invitations', [ContestController::class, 'invitations']);
    Route::get('/contests/{contestId}', [ContestController::class, 'show']);
    Route::post('/contests/{contestId}/join', [ContestController::class, 'joinAdminContest']);
    Route::post('/contests/one-vs-one', [ContestController::class, 'createOneVsOne']);
    Route::post('/contests/city-vs-city', [ContestController::class, 'createCityVsCity']);
    Route::post('/contests/{contestId}/one-vs-one/request-join', [ContestController::class, 'requestJoinOneVsOne']);
    Route::post('/contests/{contestId}/one-vs-one/select-opponent', [ContestController::class, 'selectOneVsOneOpponent']);
    Route::post('/contests/invitations/{invitationId}/respond', [ContestController::class, 'respondInvitation']);
    Route::post('/contests/{contestId}/city/join', [ContestController::class, 'joinCityContest']);
    Route::post('/contests/{contestId}/submissions', [ContestController::class, 'submitContestOutfit']);
    Route::post('/contests/{contestId}/vote', [ContestController::class, 'vote']);
});
